robot_cfg:
  kinematics:
    base_link: world
    collision_link_names:
      - lbr_iiwa_link_1
      - lbr_iiwa_link_2
      - lbr_iiwa_link_3
      - lbr_iiwa_link_4
      - lbr_iiwa_link_5
      - lbr_iiwa_link_6
      - hand_root
    collision_sphere_buffer: 0.001
    collision_spheres: spheres/iiwa14.yml
    ee_link: hand_root
    self_collision_buffer:
      lbr_iiwa_link_1: -0.02
      lbr_iiwa_link_2: -0.02
      lbr_iiwa_link_3: -0.02
      lbr_iiwa_link_4: -0.02
      lbr_iiwa_link_5: -0.02
      lbr_iiwa_link_6: -0.02

    self_collision_ignore:
      {
        lbr_iiwa_link_1: [lbr_iiwa_link_2, lbr_iiwa_link_3],
        lbr_iiwa_link_2: [lbr_iiwa_link_3, lbr_iiwa_link_4],
        lbr_iiwa_link_3: [lbr_iiwa_link_4, lbr_iiwa_link_5],
        lbr_iiwa_link_4: [lbr_iiwa_link_5, lbr_iiwa_link_6],
        lbr_iiwa_link_5: [lbr_iiwa_link_6],
        lbr_iiwa_link_6: [hand_root],
      }
    urdf_path: robot/kuka_allegro/model.urdf
    asset_root_path: robot/kuka_allegro
  
    cspace:
      joint_names:
        [
          "lbr_iiwa_joint_1",
          "lbr_iiwa_joint_2",
          "lbr_iiwa_joint_3",
          "lbr_iiwa_joint_4",
          "lbr_iiwa_joint_5",
          "lbr_iiwa_joint_6",
          "lbr_iiwa_joint_7",
        ]
      cspace_distance_weight:
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5

      null_space_weight:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0

      retract_config:
        - -0.5235987755982988
        - 0.5235987755982988
        - 0.0
        - -1.5707963267948966
        - 0.0
        - 1.0471975511965976
        - -2.0943951023931953
      max_acceleration: 15.0
      max_jerk: 500.0
