# Copied from franka.yml with modifications
robot_cfg:
  kinematics:
    base_link: world
    collision_link_names:
      - lbr_iiwa_link_1
      - lbr_iiwa_link_2
      - lbr_iiwa_link_3
      - lbr_iiwa_link_4
      - lbr_iiwa_link_5
      - lbr_iiwa_link_6
      - hand_root
    collision_sphere_buffer: 0.001
    collision_spheres: spheres/iiwa14.yml
    ee_link: hand_root
    self_collision_buffer:
      lbr_iiwa_link_1: -0.02
      lbr_iiwa_link_2: -0.02
      lbr_iiwa_link_3: -0.02
      lbr_iiwa_link_4: -0.02
      lbr_iiwa_link_5: -0.02
      lbr_iiwa_link_6: -0.02

    self_collision_ignore:
      {
        lbr_iiwa_link_1: [lbr_iiwa_link_2, lbr_iiwa_link_3],
        lbr_iiwa_link_2: [lbr_iiwa_link_3, lbr_iiwa_link_4],
        lbr_iiwa_link_3: [lbr_iiwa_link_4, lbr_iiwa_link_5],
        lbr_iiwa_link_4: [lbr_iiwa_link_5, lbr_iiwa_link_6],
        lbr_iiwa_link_5: [lbr_iiwa_link_6],
        lbr_iiwa_link_6: [hand_root],
      }
    urdf_path: robot/kuka_allegro/model.urdf
    asset_root_path: robot/kuka_allegro
  
    cspace:
      joint_names:
        ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
         "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"
        ]
      cspace_distance_weight:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0

      null_space_weight:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0

      retract_config:
        - 0.0
        - -1.3
        - 0.0
        - -2.5
        - 0.0
        - 1.0
        - 0.0
        - 0.04
        - 0.04
      max_acceleration: 15.0
      max_jerk: 500.0
