##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

collision_spheres:
    fr3_link0:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.0, 0.0, 0.075]
          "radius": 0.075
        - "center": [0.0, 0.0, 0.15]
          "radius": 0.075
    fr3_link1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.0, -0.053, 0.053]
          "radius": 0.075
        - "center": [0.0, 0.022, 0.053]
          "radius": 0.075
        - "center": [0.0, 0.097, 0.053]
          "radius": 0.075
    fr3_link2:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.0, -0.053, -0.053]
          "radius": 0.075
        - "center": [0.0, -0.128, -0.053]
          "radius": 0.075
    fr3_link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.053, 0.0, 0.053]
          "radius": 0.075
        - "center": [0.075, 0.053, 0.053]
          "radius": 0.075
        - "center": [0.075, -0.053, 0.053]
          "radius": 0.075
    fr3_link4:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [-0.053, 0.0, 0.0]
          "radius": 0.075
        - "center": [-0.053, 0.075, -0.03]
          "radius": 0.075
        - "center": [-0.053, 0.15, -0.03]
          "radius": 0.075
    fr3_link5:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.0, 0.053, 0.053]
          "radius": 0.075
        - "center": [0.0, 0.053, 0.128]
          "radius": 0.075
        - "center": [0.0, -0.053, 0.128]
          "radius": 0.075
    fr3_link6:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.075, 0.0, 0.0]
          "radius": 0.075
    fr3_link7:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.075
        - "center": [0.0, 0.053, 0.0]
          "radius": 0.075
        - "center": [0.0, 0.102, 0.045]
          "radius": 0.03
        - "center": [-0.02, 0.082, 0.045]
          "radius": 0.03
        - "center": [-0.04, 0.062, 0.045]
          "radius": 0.03
        - "center": [-0.06, 0.042, 0.045]
          "radius": 0.03
        - "center": [-0.08, 0.022, 0.045]
          "radius": 0.03
        - "center": [-0.10, 0.002, 0.045]
          "radius": 0.03
    algr_rh_palm:
        - "center": [-0.01, 0.0, -0.02]
          "radius": 0.03
        - "center": [-0.01, 0.03, -0.02]
          "radius": 0.03
        - "center": [-0.01, -0.03, -0.02]
          "radius": 0.03
        - "center": [-0.01, 0.03, -0.05]
          "radius": 0.03
        - "center": [-0.01, -0.03, -0.05]
          "radius": 0.03
        - "center": [-0.01, 0.03, -0.08]
          "radius": 0.03
        - "center": [-0.01, -0.03, -0.08]
          "radius": 0.03
    algr_rh_if_bs:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_if_px:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_if_md:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_if_ds:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_mf_bs:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_mf_px:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_mf_md:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_mf_ds:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_rf_bs:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_rf_px:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_rf_md:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_rf_ds:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_th_mp:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_th_bs:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_th_px:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
    algr_rh_th_ds:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.02]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.04]
          "radius": 0.02