collision_spheres:
  panda_link0:
    - "center": [-0.08, 0.0, 0.05]
      "radius": 0.06
    - "center": [-0.0, 0.0, 0.05]
      "radius": 0.08
  panda_link1:
    - "center": [0.0, -0.08, 0.0]
      "radius": 0.1
    - "center": [0.0, -0.03, 0.0]
      "radius": 0.1
    - "center": [0.0, 0.0, -0.12]
      "radius": 0.06
    - "center": [0.0, 0.0, -0.17]
      "radius": 0.06
  panda_link2:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.1
    - "center": [0.0, 0.0, 0.08]
      "radius": 0.1
    - "center": [0.0, -0.12, 0.0]
      "radius": 0.06
    - "center": [0.0, -0.17, 0.0]
      "radius": 0.06
  panda_link3:
    - "center": [0.0, 0.0, -0.06]
      "radius": 0.05
    - "center": [0.0, 0.0, -0.1]
      "radius": 0.06
    - "center": [0.08, 0.06, 0.0]
      "radius": 0.055
    - "center": [0.08, 0.02, 0.0]
      "radius": 0.055
  panda_link4:
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.055
    - "center": [0.0, 0.0, 0.06]
      "radius": 0.055
    - "center": [-0.08, 0.095, 0.0]
      "radius": 0.06
    - "center": [-0.08, 0.06, 0.0]
      "radius": 0.055
  panda_link5:
    - "center": [0.0, 0.055, 0.0]
      "radius": 0.05
    - "center": [0.0, 0.085, 0.0]
      "radius": 0.055
    - "center": [0.0, 0.000, -0.22]
      "radius": 0.05
    - "center": [0.0, 0.05, -0.18]
      "radius": 0.045
    - "center": [0.015, 0.08, -0.14]
      "radius": 0.03
    - "center": [0.015, 0.085, -0.11]
      "radius": 0.03
    - "center": [0.015, 0.09, -0.08]
      "radius": 0.03
    - "center": [0.015, 0.095, -0.05]
      "radius": 0.03
    - "center": [-0.015, 0.08, -0.14]
      "radius": 0.03
    - "center": [-0.015, 0.085, -0.11]
      "radius": 0.03
    - "center": [-0.015, 0.09, -0.08]
      "radius": 0.03
    - "center": [-0.015, 0.095, -0.05]
      "radius": 0.03
  panda_link6:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.05
    - "center": [0.08, 0.035, 0.0]
      "radius": 0.052
    - "center": [0.08, -0.01, 0.0]
      "radius": 0.05
  panda_link7:
    - "center": [0.0, 0.0, 0.07]
      "radius": 0.05
    - "center": [0.02, 0.04, 0.08]
      "radius": 0.025
    - "center": [0.04, 0.02, 0.08]
      "radius": 0.025
    - "center": [0.04, 0.06, 0.085]
      "radius": 0.02
    - "center": [0.06, 0.04, 0.085]
      "radius": 0.02
  base_link:
    - "center": [-0.01, 0.0, -0.02]
      "radius": 0.03
    - "center": [-0.01, 0.03, -0.02]
      "radius": 0.03
    - "center": [-0.01, -0.03, -0.02]
      "radius": 0.03
    - "center": [-0.01, 0.03, -0.05]
      "radius": 0.03
    - "center": [-0.01, -0.03, -0.05]
      "radius": 0.03
    - "center": [-0.01, 0.03, -0.08]
      "radius": 0.03
    - "center": [-0.01, -0.03, -0.08]
      "radius": 0.03
  link_0.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_1.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.02
  link_2.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_3.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_4.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_5.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.02
  link_6.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_7.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_8.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_9.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.02
  link_10.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_11.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_12.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_13.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.02
  link_14.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
  link_15.0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.02
